SELECT SSN, FNAME, LNAME 
FROM Employee
WHERE SSN IN (SELECT ESSN
	      FROM Dependent)
UNION
SELECT SSN, FNAME, LNAME 
FROM Employee
WHERE SSN IN (SELECT MGRSSN
	      FROM Department);

SELECT SSN, FNAME, LNAME 
FROM Employee
WHERE SSN IN (SELECT ESSN
			  FROM Dependent)
INTERSECT
SELECT SSN, FNAME, LNAME 
FROM Employee
WHERE SSN IN (SELECT MGRSSN
	          FROM Department);

SELECT SSN, FNAME, LNAME 
FROM Employee
WHERE SSN IN (SELECT ESSN
			  FROM Works_On)
EXCEPT
(SELECT SSN, FNAME, LNAME 
FROM Employee
WHERE SSN IN (SELECT ESSN
			  FROM Dependent)
INTERSECT
SELECT SSN, FNAME, LNAME 
FROM Employee
WHERE SSN IN (SELECT MGRSSN
			  FROM Department));


SELECT SSN, LNAME, FNAME
FROM EMPLOYEE 
WHERE NOT EXISTS( SELECT PNUMBER
				  FROM PROJECT
                  WHERE NOT EXISTS( SELECT *
            						FROM WORKS_ON
			                		WHERE PNUMBER = PNO AND ESSN = SSN));


SELECT PNUMBER, PNAME, (SELECT COUNT(*) FROM Works_On AS W WHERE P.PNUMBER = W.PNO) AS EMPLOYEE_COUNT
FROM Project As P;
        
SELECT E.SSN, E.LNAME, S.SSN, S.LNAME, P.PNAME, P.PNUMBER
FROM Employee AS E
INNER JOIN Employee S ON E.SUPPERSSN = S.SSN
INNER JOIN Works_On WE ON E.SSN = WE.ESSN
INNER JOIN Works_On WS ON S.SSN = WS.ESSN AND WE.PNO = WS.PNO
INNER JOIN Project P ON WE.PNO = P.PNUMBER
        